athombv/node-homey-meshdriver

- lib/zigbee/ZigBeeXYLightDevice.js
`value === 'temperature'` which would cause the light temperature to not be set correctly when no "light_temperature" was is given (e.g. when switching modes)
> Fixed switching to light_temperature changing to a wrong initial value

- lib/zwave/system/capabilities/onoff/BASIC.js
- lib/zwave/system/capabilities/onoff/SWITCH_BINARY.js
changed the method for BASIC command class for the onoff capability, as
the value van be anything
from 1 till 99
and 255
for to determing if it is "on"
added "reportParser" for v2 of the SWITCH_BINARY in onoff capability, as
it was missing,
it will not update the capability if a device has v2
(different value name)
also fixed the "setParser" of v2 as it was copy pasted from
SWITCH_MULTILEVEL but the values are actually different.
even though it would fall back to v1 to still trigger the device,
it could never have used the Duration property
> change onoff/BASIC & onoff/SWITCH_BINARY

- lib/zwave/ZwaveDevice.js
> [Z-Wave] update settings functions

- lib/zwave/ZwaveDevice.js
this addition will catch echo's (unwanted multiple commands) as result of the z-wave
broadcast mechanism on the central scene command class
```
2018-01-14 20:33:20 [log] [ManagerDrivers] [ZRC-90] [1] **Pre catch**: Sequence: 83, Previous Sequence: 82
2018-01-14 20:33:20 [log] [ManagerDrivers] [ZRC-90] [1] **After catch**: Sequence: 83, Previous Sequence: 82
2018-01-14 20:33:20 [log] [ManagerDrivers] [ZRC-90] [1] **Pre catch**: Sequence: 83, Previous Sequence: 83
2018-01-14 20:33:20 [log] [ManagerDrivers] [ZRC-90] [1] **Pre catch**: Sequence: 83, Previous Sequence: 83
2018-01-14 20:33:21 [log] [ManagerDrivers] [ZRC-90] [1] **Pre catch**: Sequence: 83, Previous Sequence: 83
2018-01-14 20:33:22 [log] [ManagerDrivers] [ZRC-90] [1] **Pre catch**: Sequence: 84, Previous Sequence: 83
```
also …
> [Z-Wave] catch central scene echo's

- lib/zigbee/ZigBeeDevice.js
capabilityObj is always the first item in capabilitiesOpts because "x.capability = capabilityId" always returns true. so when you use multiple different clusterIds in the capabilitiesOpts, it is possible that the found clusterId is not the clusterId for the given capabilityId.
> fixed using wrong clusterId in _registerCapabilitiesSet

- lib/zigbee/ZigBeeDevice.js
- lib/zwave/ZwaveDevice.js
`userOpts` passed to `registerCapability` calls were overwriting `systemOpts` for a particular capability/command class or capability/cluster id combination.
This could lead to unpredictable behavior if multiple drivers defined by the same app are in use.
For example:
Suppose two different device types with two different drivers from the same brand are in use. Both devices support the same capability/command class combination. One of the drivers provides `userOpts`, but the other doesn't. The one using the default settings may end up using the `userOpts` from the other driver, if that driver is initialized last.
(`object.assign` modifies the first object passed to it)
> Prevent registerCapability overwriting systemOpts

- lib/zwave/system/capabilities/measure_current/METER.js
- lib/zwave/system/capabilities/measure_power/METER.js
- lib/zwave/system/capabilities/measure_voltage/METER.js
- lib/zwave/system/capabilities/meter_power/METER.js
- lib/zwave/system/capabilities/powerFactor/METER.js
- lib/zwave/system/capabilities/powerReactive/METER.js
- lib/zwave/system/capabilities/powerTotalApparent/METER.js
Z-Wave only check for Scale 2 prop if present, seems that some devices do not send that parameter (when it is zero assumably).
> Z-Wave: improve meter parsers

- lib/MeshDevice.js
Fixes some weird type errors where `this._pollIntervals` is null or undefined (https://sentry.io/athom-bv/comikeatradfri-rv/issues/738943815).
> Prevent type error

- lib/zwave/system/capabilities/dim/windowcoverings/SWITCH_MULTILEVEL.js
- lib/zwave/system/capabilities/windowcoverings_tilt_set/SWITCH_MULTILEVEL.js
This affects the following capabilities:
- dim (for device class windowcoverings)
- windowcoverings_tilt_set
> Fixes issue with edge values (0/1) for windowcoverings capabilities

- lib/zwave/system/capabilities/measure_current/METER.js
- lib/zwave/system/capabilities/measure_power/METER.js
- lib/zwave/system/capabilities/measure_voltage/METER.js
- lib/zwave/system/capabilities/meter_power/METER.js
- lib/zwave/system/capabilities/powerReactive/METER.js
- lib/zwave/system/capabilities/powerTotalApparent/METER.js
This affects the following capabilities:
- measure_current
- measure_power
- measure_voltage
- meter_power
- powerReactive
- powerTotalApparent
> Fixes command class meter v4 report parsers

- lib/zigbee/ZigBeeDevice.js
It expects a `get energyMap(){}` on the inheriting instance. This map should contain an object with productIds and their associated energy object. This allows for setting different energy objects on device instances of the same driver based on the zigbee productId.
@KyleAthom @WeeJeWel do you think this is a good idea? When working on energy for `com.ikea.tradfri` I had to figure out a way to set different energy objects based on ZigBee `productId` (since there are many different bulbs supported by a single driver). This allows for setting an `energyMap` object on the `ZigBeeDevice` instance. This `energyMap` object contains the energy objects per device (based on `productId`).
> Adds functionality that handles finding and setting energy properties

- lib/zigbee/ZigBeeDevice.js
When registering a capability (e.g. `onoff.output`) the system capability could not found due to the different capabilityId. This commit changes that before looking for system capabilities the capabilityId is spliced to determine the root capability.
> Fixes registering an extended system capability

- lib/zwave/ZwaveDevice.js
This is a breaking change, `refreshCapabilityValue` now returns a Promise which should be catched. Benefit of this change is that `refreshCapabilityValue` can now be awaited to get the actual value which was retrieved.
> [ZwaveDevice] Promisifies refreshCapabilityValue

- lib/zwave/ZwaveDevice.js
This allows developers to directly call the set commands for a registered capability/commandClass combination.
> Extract _setCapabilityValue and expose via public executeCapabilitySetCommand

- lib/zigbee/ZigBeeDevice.js
This prevents _setEnergyObjectByProductId() from executing before the node has been inited.
> [ZigBee] Move _setEnergyObjectByProductId() to __meshInit event

- lib/zigbee/ZigBeeDevice.js
- lib/zwave/ZwaveDevice.js
This allows for sending different set commands from within specific system capability set parsers.
> When a capabilitySetParser returns null the set command will be ignored

- lib/zigbee/ZigBeeLightDevice.js
The `dim` and `onoff` capabilities used to be completely separate. But this was not inline with other implementations on Homey (e.g. for Z-Wave light devices). When a light is turned off, the dim level should reflect that the device is off (hence being zero). When the light is turned on again the dim level should be reset to the value before it was turned off.
This PR bundles the `onoff` and `dim` capabilities and makes sure this behaviour is corrected. Main change, after a light is turned on the dim value is requested from the device and updated on Homey. Further, the `dim` capability follows the `onoff` capability and vice versa.
> Fixes dim and onoff interaction for ZigBeeLightDevice

- package.json
Otherwise it will generate errors in package.json when running on node > 8.
> Fixes package.json node engine >=8

- lib/zwave/system/capabilities/dim/SWITCH_MULTILEVEL.js
Buffer.from() is a fix for difference between V3/V4 dimming duration XML specification.
> Fixes SWITCH_MULTILEVEL_SET V4

- lib/zwave/system/capabilities/dim/SWITCH_MULTILEVEL.js
- lib/zwave/system/capabilities/dim/windowcoverings/SWITCH_MULTILEVEL.js
- lib/zwave/system/capabilities/windowcoverings_set/SWITCH_MULTILEVEL.js
- lib/zwave/system/capabilities/windowcoverings_tilt_set/SWITCH_MULTILEVEL.js
Buffer.from() is a fix for difference between V3/V4 dimming duration XML specification
> Fixes all SWITCH_MULTILEVEL_SET V4 parsers

- lib/zwave/system/commandclasses/NOTIFICATION/index.js
Instead of overwriting the `(Parsed)` we are adding a `(Parsed 2)` for COMMAND_CLASS_NOTIFICATION.
`(Parsed)` and `(Parsed 2)` are both created using the same logic so they should be the same, since we don't use `(Parsed 2)` anywhere I'm adding `(Parsed)` for clarity.
> fix: add missing parsed attribute
